-- MySQL Script generated by MySQL Workbench
-- Thu Jun 16 14:09:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbEtablissement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbEtablissement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbEtablissement` DEFAULT CHARACTER SET utf8mb4 ;
USE `dbEtablissement` ;

-- -----------------------------------------------------
-- Table `dbEtablissement`.`ETABLISSEMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`ETABLISSEMENTS` (
  `id_etablissement` INT NOT NULL AUTO_INCREMENT,
  `nom_etablissement` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_etablissement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`PROMOTIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`PROMOTIONS` (
  `id_promotion` INT NOT NULL AUTO_INCREMENT,
  `nom_promotion` VARCHAR(45) NOT NULL,
  `id_etablissement` INT NOT NULL,
  `année` INT(4) NOT NULL,
  PRIMARY KEY (`id_promotion`),
  INDEX `fk_PROMOTIONS_ETABLISSEMENTS1_idx` (`id_etablissement` ASC) VISIBLE,
  CONSTRAINT `fk_PROMOTIONS_ETABLISSEMENTS1`
    FOREIGN KEY (`id_etablissement`)
    REFERENCES `dbEtablissement`.`ETABLISSEMENTS` (`id_etablissement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`ELEVES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`ELEVES` (
  `id_eleve` INT NOT NULL,
  `identifiant` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `premon` VARCHAR(255) NOT NULL,
  `id_promotion` INT NOT NULL,
  `date_naissance` DATE NULL,
  `email` VARCHAR(255) NULL,
  `telephone` VARCHAR(10) NULL,
  INDEX `fk_ELEVES_PROMOTIONS1_idx` (`id_promotion` ASC) VISIBLE,
  PRIMARY KEY (`id_eleve`, `id_promotion`),
  CONSTRAINT `fk_ELEVES_PROMOTIONS1`
    FOREIGN KEY (`id_promotion`)
    REFERENCES `dbEtablissement`.`PROMOTIONS` (`id_promotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`MATIERES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`MATIERES` (
  `id_matiere` INT NOT NULL AUTO_INCREMENT,
  `nom_matiere` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_matiere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`ENSEIGNANTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`ENSEIGNANTS` (
  `id_enseignant` INT NOT NULL,
  `identifiant` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `date_naissance` DATE NULL,
  `email` VARCHAR(255) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_enseignant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`SALLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`SALLES` (
  `id_salle` INT NOT NULL AUTO_INCREMENT,
  `id_etablissement` INT NOT NULL,
  `nom_salle` VARCHAR(255) NOT NULL,
  `caracteristique` VARCHAR(255) NULL,
  PRIMARY KEY (`id_salle`, `id_etablissement`),
  INDEX `fk_SALLES_ETABLISSEMENTS1_idx` (`id_etablissement` ASC) VISIBLE,
  CONSTRAINT `fk_SALLES_ETABLISSEMENTS1`
    FOREIGN KEY (`id_etablissement`)
    REFERENCES `dbEtablissement`.`ETABLISSEMENTS` (`id_etablissement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`ENSEIGNANTS_has_MATIERES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`ENSEIGNANTS_has_MATIERES` (
  `id_enseignant` INT NOT NULL,
  `id_matiere` INT NOT NULL,
  PRIMARY KEY (`id_enseignant`, `id_matiere`),
  INDEX `fk_ENSEIGNANTS_has_MATIERES_MATIERES1_idx` (`id_matiere` ASC) VISIBLE,
  INDEX `fk_ENSEIGNANTS_has_MATIERES_ENSEIGNANTS1_idx` (`id_enseignant` ASC) VISIBLE,
  CONSTRAINT `fk_ENSEIGNANTS_has_MATIERES_ENSEIGNANTS1`
    FOREIGN KEY (`id_enseignant`)
    REFERENCES `dbEtablissement`.`ENSEIGNANTS` (`id_enseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENSEIGNANTS_has_MATIERES_MATIERES1`
    FOREIGN KEY (`id_matiere`)
    REFERENCES `dbEtablissement`.`MATIERES` (`id_matiere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`PLANNING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`PLANNING` (
  `id_planning` INT NOT NULL AUTO_INCREMENT,
  `id_salle` INT NULL,
  `id_promotion` INT NULL,
  `date` DATE NOT NULL,
  `heure_debut` TIME NOT NULL,
  `heure_fin` TIME NOT NULL,
  `id_enseignant` INT NULL,
  `id_matiere` INT NULL,
  INDEX `fk_PLANNING_PROMOTIONS1_idx` (`id_promotion` ASC) VISIBLE,
  PRIMARY KEY (`id_planning`),
  INDEX `fk_PLANNING_SALLES1_idx` (`id_salle` ASC) VISIBLE,
  INDEX `fk_PLANNING_ENSEIGNANTS_has_MATIERES1_idx` (`id_enseignant` ASC, `id_matiere` ASC) VISIBLE,
  CONSTRAINT `fk_PLANNING_PROMOTIONS1`
    FOREIGN KEY (`id_promotion`)
    REFERENCES `dbEtablissement`.`PROMOTIONS` (`id_promotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLANNING_SALLES1`
    FOREIGN KEY (`id_salle`)
    REFERENCES `dbEtablissement`.`SALLES` (`id_salle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLANNING_ENSEIGNANTS_has_MATIERES1`
    FOREIGN KEY (`id_enseignant` , `id_matiere`)
    REFERENCES `dbEtablissement`.`ENSEIGNANTS_has_MATIERES` (`id_enseignant` , `id_matiere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`ADMINISTRATEURS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`ADMINISTRATEURS` (
  `id_administrateur` INT NOT NULL AUTO_INCREMENT,
  `identifiant` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_administrateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEtablissement`.`ETABLISSEMENTS_has_UTILISATEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEtablissement`.`ETABLISSEMENTS_has_UTILISATEUR` (
  `id_etablissement` INT NOT NULL,
  `ENSEIGNANTS_id_enseignant` INT NOT NULL,
  `ADMINISTRATEUR_id_administrateur` INT NOT NULL,
  `ELEVES_id_promotion` INT NOT NULL,
  PRIMARY KEY (`id_etablissement`),
  INDEX `fk_ETABLISSEMENTS_has_UTILISATEUR_ETABLISSEMENTS1_idx` (`id_etablissement` ASC) VISIBLE,
  INDEX `fk_ETABLISSEMENTS_has_UTILISATEUR_ENSEIGNANTS1_idx` (`ENSEIGNANTS_id_enseignant` ASC) VISIBLE,
  INDEX `fk_ETABLISSEMENTS_has_UTILISATEUR_ADMINISTRATEUR1_idx` (`ADMINISTRATEUR_id_administrateur` ASC) VISIBLE,
  INDEX `fk_ETABLISSEMENTS_has_UTILISATEUR_ELEVES1_idx` (`ELEVES_id_promotion` ASC) VISIBLE,
  CONSTRAINT `fk_ETABLISSEMENTS_has_UTILISATEUR_ETABLISSEMENTS1`
    FOREIGN KEY (`id_etablissement`)
    REFERENCES `dbEtablissement`.`ETABLISSEMENTS` (`id_etablissement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ETABLISSEMENTS_has_UTILISATEUR_ENSEIGNANTS1`
    FOREIGN KEY (`ENSEIGNANTS_id_enseignant`)
    REFERENCES `dbEtablissement`.`ENSEIGNANTS` (`id_enseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ETABLISSEMENTS_has_UTILISATEUR_ADMINISTRATEUR1`
    FOREIGN KEY (`ADMINISTRATEUR_id_administrateur`)
    REFERENCES `dbEtablissement`.`ADMINISTRATEURS` (`id_administrateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ETABLISSEMENTS_has_UTILISATEUR_ELEVES1`
    FOREIGN KEY (`ELEVES_id_promotion`)
    REFERENCES `dbEtablissement`.`ELEVES` (`id_promotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
